services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: actron-air-esphome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./ha-config:/config
    environment:
      - TZ=Australia/Sydney
