title: Actron Air
views:
  - title: Forecast
    icon: mdi:weather-partly-cloudy
    cards:
      - type: custom:actron-air-esphome-card
        entity_prefix: actron_air_esphome
        zone_count: 8
      - type: custom:actron-air-esphome-card
        entity_prefix: actron_air_esphome
        zone_count: 4
        zones:
          - name: Kitchen
          - name: Bedrooms
          - name: Office
          - name: Living Room
